name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  PYTHON_VERSION: '3.11'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest-cov pytest-asyncio
    
    - name: Create test environment file
      run: |
        cat > .env.test << EOF
        BASE_RPC_URL=https://base-sepolia.g.alchemy.com/v2/test
        PRIVATE_KEY=0x1111111111111111111111111111111111111111111111111111111111111111
        WALLET_ADDRESS=0x1111111111111111111111111111111111111111
        TELEGRAM_BOT_TOKEN=test_token
        TELEGRAM_CHAT_ID=123456789
        BASESCAN_API_KEY=test_api_key
        DRY_RUN_MODE=true
        LOG_LEVEL=DEBUG
        EOF
    
    - name: Run tests with coverage
      env:
        PYTHONPATH: ${{ github.workspace }}
      run: |
        pytest tests/ \
          --cov=src \
          --cov-report=xml \
          --cov-report=term-missing \
          -v
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false